MBE/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inventory.urls')),
    path("select2/", include("django_select2.urls")),
]

inventory/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('gggg',include('django.contrib.auth.urls')),
    path('', views.home, name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='inventory/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('products/', views.products, name="products"),
    path('orders/', views.orders, name="orders"),
    path('seller_order/<str:pk>', views.seller_order, name="seller_order"),
    path('seller/', views.seller, name="seller"),
    path('create_order/', views.createOrder, name="create_order"),
    path('update_order/<str:pk>', views.updateOrder, name="update_order"),
    path('delete_order/<str:pk>', views.deleteOrder, name="delete_order"),
    path('create_seller/', views.createSeller, name="create_seller"),
    path('delete_seller/<str:pk>', views.deleteSeller, name="delete_seller"),
    path('update_seller/<str:pk>', views.updateSeller, name="update_seller"),
    path('reset_pw/<str:pk>', views.resetPw, name="reset_pw"),
    path('create_product/', views.createProduct, name="create_product"),
    path('update_product/<str:pk>', views.updateProduct, name="update_product"),
    path('delete_product/<str:pk>', views.deleteProduct, name="delete_product"),
    path('edit_product_qty/<str:pk>', views.editProductQty, name="edit_product_qty"),
    path('list_log/', views.listLog, name="list_log"),
    path('inbound/', views.inbound, name="inbound"),
    path('create_inbound/', views.createInbound, name="create_inbound"),
    path('create_np_inbound/', views.createNpInbound, name="create_np_inbound"),
    path('approve_inbound/<str:pk>', views.approveInbound, name="approve_inbound"),
    path('reject_inbound/<str:pk>', views.rejectInbound, name="reject_inbound"),
    path('pdf_product/', views.PDFProduct.as_view(), name="pdf_product"),
    path('pdf_order/', views.PDFOrder.as_view(), name="pdf_order"),
    path('pdf_seller/', views.PDFSeller.as_view(), name="pdf_seller"),
    path('pdf_log/', views.PDFLog.as_view(), name="pdf_log"),
    path('pdf_inbound/', views.PDFInbound.as_view(), name="pdf_inbound"),
    path('outbound/', views.outbound, name="outbound"),
    path('create_outbound/', views.createOutbound, name="create_outbound"),
    path('approve_outbound/<str:pk>', views.approveOutbound, name="approve_outbound"),
    path('reject_outbound/<str:pk>', views.rejectOutbound, name="reject_outbound"),
    path('pdf_outbound/', views.PDFOutbound.as_view(), name="pdf_outbound"),  
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class User(AbstractUser):
    is_seller = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=11, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    UNIT = (
        ('PCS','PCS'),
        ('BOX','BOX'),
        ('PACK','PACK'),
        ('BOTTLE','BOTTLE'),
        ('OTHER','OTHER'),
    )

    date_created = models.DateTimeField(auto_now_add=True, null=True)
    sku_code = models.CharField(max_length=200, primary_key=True)
    product_name = models.CharField(max_length=200, null=True)
    unit = models.CharField(max_length=200, choices=UNIT, null=True)
    product_quantity = models.PositiveIntegerField(null=True)
    product_price = models.FloatField(validators=[MinValueValidator(0.0)])
    location = models.CharField(max_length=200, null=True)
    rack = models.CharField(max_length=200, null=True)  
    pallet = models.CharField(max_length=200, null=True)
    remarks = models.CharField(max_length=200, null=True, blank=True)


    seller = models.ForeignKey(Seller, to_field='user_id', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.sku_code

class Order(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Out of Delivery','Out of Delivery'),
        ('Completed','Completed'),
        ('Rejected','Rejected'),
    )

    order_id = models.CharField(max_length=200, primary_key=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    order_quantity = models.PositiveIntegerField(null=True, validators=[MinValueValidator(1)])
    platform = models.CharField(max_length=200, null=True)
    awb = models.CharField(max_length=200, null=True)
    courier = models.CharField(max_length=200, null=True)
    remarks = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=200, choices=STATUS, null=True)

    seller = models.ForeignKey(Seller, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.order_id

class TransactionProductQty(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    user = models.CharField(max_length=200, null=True)
    action = models.CharField(max_length=200, null=True)
    qty = models.IntegerField(null=True)
    current_qty = models.PositiveIntegerField(null=True)
    reason = models.CharField(max_length=200, null=True)
    record_product = models.CharField(max_length=200, null=True)
    
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)

class Inbound(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Approved','Approved'),
        ('Rejected','Rejected'),
    )

    UNIT = (
        ('PCS','PCS'),
        ('BOX','BOX'),
        ('PACK','PACK'),
        ('BOTTLE','BOTTLE'),
        ('OTHER','OTHER'),
    )

    date_created = models.DateTimeField(auto_now_add=True, null=True)
    product_name = models.CharField(max_length=200, null=True)
    sku_code = models.CharField(max_length=200, null=True)
    unit = models.CharField(max_length=200, choices=UNIT, null=True)
    product_quantity = models.IntegerField(null=True)
    product_price = models.FloatField(validators=[MinValueValidator(0.0)])
    remarks = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=200, choices=STATUS, default='Pending')

    seller = models.ForeignKey(Seller, to_field='user_id', null=True, on_delete=models.SET_NULL)

class Outbound(models.Model):
    
    STATUS = (
       ('Pending','Pending'),
       ('Approved', 'Approved'),
        ('Out of Delivery','Out of Delivery'),
        ('Completed','Completed'),
        ('Rejected','Rejected'),
    )

    PLATFORM = (('Shopee', 'Shopee'),
    ('Lazada', 'Lazada'),
    ('Other', 'Other'),
    )

    order_id = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    order_quantity = models.PositiveIntegerField(null=True, validators=[MinValueValidator(1)])
    platform = models.CharField(max_length=200, choices=PLATFORM, null=True)
    
    remarks = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=200, choices=STATUS, default='Pending')
    seller = models.ForeignKey(Seller, to_field='user_id', null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, to_field='sku_code', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.product)

inventory/templates/inventory/create_form.html
{% extends 'inventory/main.html' %}

{% block content %}

  <div class="row">
    <div class="col-md 6">
      <div class="card card-body">
        <form action="" method="POST" autocomplete="off">
          {% csrf_token %}
          <div class="tableFixHead">
          <table class="table input-table">
            <thead>
              <tr>
                {% for form in formset %}
                  {% if forloop.first %}
                    {% for field in form  %}
                      <th scope="col">{{field.label_tag}}</th>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              </tr>
            </thead>
            <tbody class="">
              {{ formset.management_form }}
              {% for form in formset %}
                {% if not form.DELETE.value %}
                  <tr>
                    {% for field in form  %}
                      {% if not forloop.last %}
                        {% if field.errors %}
                          <td class="highlight-red">
                            <div class="tooltip">
                              <span class="tooltiptext">
                                {% for error in field.errors %}
                                  {{error}}
                                {% endfor %}
                              </span>
                            </div>
                            {{ field }}
                          </td>
                        {% else %}
                          <td>{{ field }}</td>
                        {% endif %}
                      {% else %}
                        <td class="text-center"> <div class="hidden">{{ field }}</div><button  class="btn btn-sm btn-danger" name='del_button' type="button" onclick="del_row(this)"><i class="fa fa-trash-alt"></i> Delete</button></td>
                      {% endif %}
                    {% endfor %}
                  </tr>
                {% endif %}
              
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="mt-3">
          <input class="btn btn-success" type="submit" name="Submit">
          <button class="btn btn-primary" type="button" id="add_more"><i class="fa fa-fw fa-plus-circle"></i> Add More</button>
        </div>
        </form>
      </div>
    </div>
  </div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
   
    $('#add_more').click(function() {
      cloneMore('.table tbody tr:last', 'form');
    });
    
    function cloneMore(selector, type) {
      var newElement = $(selector).clone(true);
      var total = $('#id_' + type + '-TOTAL_FORMS').val();
      newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
      });
      newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
      });
      total++;
      $('#id_' + type + '-TOTAL_FORMS').val(total);
      $(selector).after(newElement);
    }

    function del_row(element){
      //hide row
      element.parentNode.parentNode.classList.add("hidden");

      //mark row as deleted
      element.parentNode.getElementsByTagName("input")[0].checked = true;
    }
  </script>

  <script type="text/javascript">
    $(document).ready(function() {
      // prevent default for enter
      $(window).keydown(function(event){
        if(event.keyCode == 13 || event.keyCode == 40 || event.keyCode == 38) {
          event.preventDefault();
          return false;
        }
      });

      $table_fields=$(".form-control");
		  $('tr > td > select').select2();
    });

    //KEYBOARD EVENT CODES
    // 13=enter
    // 37=left arrow
    // 38=up arrow
    // 39=right arrow
    // 40=down arrow
    var max_col=6

    $(document).on('keydown', 'input.form-control', function(event) {
      var element="input.form-control:not(:hidden)"  
        switch(event.keyCode){
          case 13: 
          case 40:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber + max_col] != null) {
                nextBox = textboxes[currentBoxNumber + max_col];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
          case 38:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber - max_col] != null) {
                nextBox = textboxes[currentBoxNumber - max_col];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
          case 37:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber - 1] != null) {
                nextBox = textboxes[currentBoxNumber - 1];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
          case 39:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber + 1] != null) {
                nextBox = textboxes[currentBoxNumber + 1];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
        }
    });
  </script>
{% endblock %}

inventory/templates/inventory/create_inbound_form.html
{% extends 'inventory/main.html' %}

{% block content %}
  <div class="row">
    <div class="col-md">

		<div class="card card-body">
            <h3>Inbound</h3>
            <!-- Hidden Form to add new product -->
            <form method="GET" action="{% url 'create_np_inbound' %}">
			    {% csrf_token %}
			    <input type="submit" class="btn btn-primary float-right" value="New Product">
		    </form>
		</div>
		<br>
		<br>
    <div class="col-md 6">
      <div class="card card-body">
        <form action="" method="POST" autocomplete="off">
          {% csrf_token %}
          <div class="tableFixHead">
          <table class="table input-table">
            <thead>
              <tr>
                {% for form in formset %}
                  {% if forloop.first %}
                    {% for field in form  %}
                      <th scope="col">{{field.label_tag}}</th>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              </tr>
            </thead>
            <tbody class="">
              {{ formset.management_form }}
              {% for form in formset %}
                {% if not form.DELETE.value %}
                  <tr>
                    {% for field in form  %}
                      {% if not forloop.last %}
                        {% if field.errors %}
                          <td class="highlight-red">
                            <div class="tooltip">
                              <span class="tooltiptext">
                                {% for error in field.errors %}
                                  {{error}}
                                {% endfor %}
                              </span>
                            </div>
                            {{ field }}
                          </td>
                        {% else %}
                          <td>{{ field }}</td>
                        {% endif %}
                      {% else %}
                        <td class="text-center"> <div class="hidden">{{ field }}</div><button  class="btn btn-sm btn-danger" name='del_button' type="button" onclick="del_row(this)"><i class="fa fa-trash-alt"></i> Delete</button></td>
                      {% endif %}
                    {% endfor %}
                  </tr>
                {% endif %}
              
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="mt-3">
          <input class="btn btn-success" type="submit" name="Submit">
          <button class="btn btn-primary" type="button" id="add_more"><i class="fa fa-fw fa-plus-circle"></i> Add More</button>
        </div>
        </form>
      </div>
    </div>
  </div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
   
    $('#add_more').click(function() {
      cloneMore('.table tbody tr:last', 'form');
    });
    
    function cloneMore(selector, type) {
      var newElement = $(selector).clone(true);
      var total = $('#id_' + type + '-TOTAL_FORMS').val();
      newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
      });
      newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
      });
      total++;
      $('#id_' + type + '-TOTAL_FORMS').val(total);
      $(selector).after(newElement);
    }

    function del_row(element){
      //hide row
      element.parentNode.parentNode.classList.add("hidden");

      //mark row as deleted
      element.parentNode.getElementsByTagName("input")[0].checked = true;
    }
  </script>

  <script type="text/javascript">
    $(document).ready(function() {
      // prevent default for enter
      $(window).keydown(function(event){
        if(event.keyCode == 13 || event.keyCode == 40 || event.keyCode == 38) {
          event.preventDefault();
          return false;
        }
      });

      $table_fields=$(".form-control");
		  $('tr > td > select').select2();
    });

    //KEYBOARD EVENT CODES
    // 13=enter
    // 37=left arrow
    // 38=up arrow
    // 39=right arrow
    // 40=down arrow
    var max_col=6

    $(document).on('keydown', 'input.form-control', function(event) {
      var element="input.form-control:not(:hidden)"  
        switch(event.keyCode){
          case 13: 
          case 40:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber + max_col] != null) {
                nextBox = textboxes[currentBoxNumber + max_col];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
          case 38:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber - max_col] != null) {
                nextBox = textboxes[currentBoxNumber - max_col];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
          case 37:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber - 1] != null) {
                nextBox = textboxes[currentBoxNumber - 1];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
          case 39:
            textboxes = $(element);
            currentBoxNumber = textboxes.index(this);
            
            if (textboxes[currentBoxNumber + 1] != null) {
                nextBox = textboxes[currentBoxNumber + 1];
                nextBox.focus();
                nextBox.select();
            }
            event.preventDefault();
            return false;
            break;
        }
    });
  </script>
{% endblock %}

inventory/templates/inventory/delete_order.html
{%  extends 'inventory/main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md 6">
        <div class="card card-body">

            <p>Are you sure want to delete "{{order}}"</p>

            <form action = "{% url 'delete_order' order.order_id %}" method = "POST">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'orders' %}">Cancel</a>

            </form>

        </div>
    </div>
</div>

{% endblock %}

inventory/templates/inventory/delete_product.html
{%  extends 'inventory/main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md 6">
        <div class="card card-body">

            <p>Are you sure want to delete "{{product}}"</p>

            <form action = "{% url 'delete_product' product.sku_code %}" method = "POST">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'products' %}">Cancel</a>

            </form>

        </div>
    </div>
</div>

{% endblock %}

inventory/templates/inventory/delete_seller.html
{%  extends 'inventory/main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
    <div class="col-md 6">
        <div class="card card-body">

            <p>Are you sure want to delete "{{seller}}"</p>

            <form action = "{% url 'delete_seller' seller.user_id %}" method = "POST">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" name="Confirm">
                <a class="btn btn-warning" href="{% url 'seller_order' seller.user_id %}">Cancel</a>

            </form>

        </div>
    </div>
</div>

{% endblock %}

inventory/templates/inventory/home.html
{% extends 'inventory/main.html' %}

{% block content %}

{% include 'inventory/status.html' %}

<br>

<div class="row">
    <div class="col-md">


        <div class="card card-body">

            <table class="table">
                <tr>
                    <th>Codes</th>
                    <th>Product Name</th>
                    <th>Location</th>
                    <th>Rack</th>
                    <th>Pallet</th>
                    <th>Units</th>
                    <th>Orders</th>
                    <th>Stock</th>
                    <th>Seller</th>


                </tr>

                {% for product in products %}
                <tr>
                    <td>{{product.sku_code}}</td>
                    <td>{{product.product_name}}</td>
                    <td>{{product.location}}</td>
                    <td>{{product.rack}}</td>
                    <td>{{product.pallet}}</td>
                    <td>{{product.unit}}</td>
                    <td>{{product.order_set.all.count}}</td>
                    <td>{{product.product_quantity}}</td>
                    <td>{{product.seller.name}}</td>

                </tr>

                {% endfor %}

            </table>
            {% include 'inventory/pagination.html' with page_obj=products request=request only%}
        </div>
    </div>

</div>

{% endblock %}

inventory/templates/inventory/main.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>MBE</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
		<link <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
		<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	</head>
	<body>
		{%  include 'inventory/nav.html' %}
		  {% if messages %}
				{% for message in messages %}
			  	<div class="alert 
			  	{% if message.level_tag == 'debug' %}
			  		alert-primary
			  	{% elif message.level_tag == 'info'%}
			  		alert-info
			  	{% elif message.level_tag == 'success'%}
			  		alert-success
			  	{% elif message.level_tag == 'warning'%}
			  		alert-warning
			  	{% elif message.level_tag == 'error'%}
			  		alert-danger
			  	{% else %}
			  		alert-secondary
			  	{% endif %}

			  	alert-dismissible fade show" role="alert">
	          {% if message.extra_tags %}
		          <strong>{{message.extra_tags}}</strong>
	          	<br>
	          {% endif %}
	          <i>{{message}}</i>
					  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					    <span aria-hidden="true">&times;</span>
					  </button>
					</div>
				{% endfor %}
		  {% endif %}

		<div class="container-fluid">
		{% block content %}



		{% endblock %}
	    </div>
		
		
		
	</body>

	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

inventory/templates/inventory/pagination.html
{% load query_transform_template_tags %}
{% if page_obj.paginator.num_pages > 1 %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
                        <span aria-hidden="true">Previous</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="?{% query_transform request page=1 %}">1</a></li>
            {% endif %}
            
            {% if page_obj.previous_page_number > 1 %}
                <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
            </li>

            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
            {% endif %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% query_transform request page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
                </li>
                <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

inventory/templates/inventory/products.html
{% extends 'inventory/main.html' %}

{% block content %}


<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h3>Product</h3>
			<form method="get">
				{{myFilter.form}}
				<button class="btn btn-primary" type="submit">Search</button>
			</form>
		</div>
		<!-- 		Hidden Form to apply filters to pdf -->
		<form method="post" action="{% url 'pdf_product' %}" target="_blank">
			{% csrf_token %}
			<input type="hidden" name="sku_code" value="{{sku_code}}">
			<input type="hidden" name="product_name" value="{{product_name}}">
			<input type="hidden" name="seller" value="{{seller}}">
			<input type="submit" class="btn btn-secondary float-right" value="Export PDF">
		</form>
		
		<br>
		<br>
		<a class="btn btn-primary btn-sm btn-block" href="{% url 'create_product' %}">Create New Products</a>
		<div class="card card-body">

			<table class="table">
				<tr>
					<th>Codes</th>
					<th>Product Name</th>
					<th>Location</th>
					<th>Rack</th>
					<th>Pallet</th>
					<th>Units</th>
					<th>Qty</th>
					<th>Seller</th>
					<th>Edit Quantity</th>
					<th>Update</th>
					<th>Delete</th>
				</tr>

				{% for product in products %}
				<tr>
					<td>{{product.sku_code}}</td>
					<td>{{product.product_name}}</td>
					<td>{{product.location}}</td>
					<td>{{product.rack}}</td>
					<td>{{product.pallet}}</td>
					<td>{{product.unit}}</td>
					<td>{{product.product_quantity}}</td>
					<td>{{product.seller.user}}</td>
					<td><a class="btn btn-sm btn-info" href="{% url 'edit_product_qty' product.sku_code %}">Edit</a></td>
					<td><a class="btn btn-sm btn-info" href="{% url 'update_product' product.sku_code %}">Update</a>
					</td>
					{% if not product.order_set.all %}
					<td><a class="btn btn-sm btn-danger" href="{% url 'delete_product' product.sku_code %}">Delete</a>
					</td>
					{% else %}
					<td></td>
					{% endif %}
					
				</tr>

				{% endfor %}

			</table>
		    {% include 'inventory/pagination.html' with page_obj=products request=request only%}
		</div>
	</div>

</div>

{% endblock content %}